version: '3.0'
services:
    php:
        build: .
        ports:
            - "80:80"
        volumes:
            - ./../code:/var/www/html
        networks:
            - backend
networks:
    backend:
